- name: Create VLANs using templates
  hosts: all
  vars:
    vlan_id: 40
    vlan_name: Guest

  tasks:
    - name: Render VLAN template to file
      template:
        src: lab5_vlan_template.j2
        dest: vlan_{{ vlan_id }}.cfg

    - name: Apply VLAN config from rendered template
      ios_config:
        src: vlan_{{ vlan_id }}.cfg
